### ISSUE TITLE
Community outreach

### ISSUE THREAD

**Issue by KenRiehle** [Tyler-IN/MnB2-Bannerlord-CommunityPatch#18]
If it helps Tyler there are mods that do some of the things we request but they are not grouped into one mod and there only sort of working they way they are supposed to.

**Comment by Tyler-IN** [comment]
Yeah, I need a social/community liason to try to contact and round up mod authors to contribute.

I don't want to just straight up steal code and fixes from people. Word is going to get around though.

**Comment by Tyler-IN** [comment]
I need help from anyone that is willing to reach out and get mod authors together to work on fixes.
I can add collaborators to this project, accept PRs from forks, and add other patches if I get permission from other authors.

**Comment by KenRiehle** [comment]
sounds great I'll work on that.

**Comment by KenRiehle** [comment]
Hey btw I need to get your email send it to me through kenholly1212@gmail.com we have 2 modders that have agreed to join the community project there waiting to hear from you.

**Comment by KenRiehle** [comment]
I have about 6 to 10 modders wanting to join the Community to help out. They all have mods of NEXUS. I explained to them that any contribution would help with code, and testing and that having a community patch that fixes many issues is so much smarter then a whole lot of small mods that fix 1 or 2 at a time. They all agreed. I even have the guy that created the docs on how to make XML files he is great at documenting.

**Comment by Tyler-IN** [comment]
Could you please just direct them to post a reply in the thread here or to my Discord account?
They need to have GitHub accounts to be able to contribute.

**Comment by tynakuh** [comment]
Could we look into clarification of the scope of this project? I'm one of the modders who was reached out to, but I don't believe some of my mods are entirely valid for this, as we can't be sure if they were part of the design decision of the game. (i.e. daily troop xp not being multiplied by stack size, just once). Looking into porting over the more clear cut things that are clearly unimplemented/bugs

**Comment by Tyler-IN** [comment]
Anything you think was originally intended for the base game that is not working as expected should be added here.

Optional features that improve the QoL of the game can come later as optional features.

The saving of mod options capability is already implemented for the sake of disabling the intro videos (otherwise debugging would be really annoying) and capturing FCEs in diagnostic reports. It can be extended to allow users to select which optional features should be enabled. No "enhancement only" features should be enabled by default unless they either are overwhelmingly improving QoL or overwhelmingly expected by the M&B community.

E.g. Autoblock would be an optional enhancement feature. It is probably better off as a separate mod.

**Comment by Jayshua83** [comment]
I have been reaching out to authors as I see all these new mods patching Vanilla bugs! :)

I am not a part of the "team" but I'll do my part to nudge authors here!

Less overall mods is good!
